MACOSX_SDK_VERSION:        # [osx and x86_64]
  - "11.0"                 # [osx and x86_64]
c_stdlib_version:          # [(osx and x86_64) or linux]
  - "11.0"                 # [osx and x86_64]
  - "2.28"                 # [linux]
folly_build_ext:
  - None
  - "jemalloc"  # [not win]
